CREATE OR REPLACE T_FIN
    (CUST_ID NUMBER,
    CUST_NAME VARCHAR(10),
    CUST_VALUE NUMBER
    )
INSERT INTO T_FIN
    (1,'A',10)

CREATE OR REPLACE T_CUST_DETAIL
    (CUST_ID NUMBER,
    CUST_ADDRESS VARCHAR(10),
    CUST_IS_ACTIVE BOOLEAN
    )
INSERT INTO T_FIN
    (1,'ABC',TRUE);

SELECT 
    T_FIN.CUST_ID,
    T_CUST_DETAIL.CUST_ADDRESS
FROM
    T_FIN LEFT JOIN T_CUST_DETAIL ON CUST_ID;

DELETE FROM T_FIN 
WHERE CUST_ID = 1;

UPDATE T_FIN
    SET CUST_NAME='B' WHERE CUST_ID=1;

TRUNCATE TABLE T_FIN;

DROP TABLE T_FIN;

SELECT 
    COUNT(CUST_ID) AS TOTAL_CUST
FROM 
    T_FIN;

SELECT CUST_ID, CUST_VAL FROM T_FIN1
INTERSECT|UNION|MINUS
SELECT CUST_ID, CUST_VAL FROM T_FIN2

SELECT CUST_ID, CUST_VAL FROM T_FIN1
INTERSECT|UNION|MINUS
SELECT CUST_ID, CUST_VAL FROM T_FIN2